### ISSUE TITLE
MissingContent when trying to login

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyrings.firefox#1]
```
>>> from keyrings import firefox
>>> cl = firefox.Client()
>>> cl.login()
Firefox email: jaraco@jaraco.com
Firefox password: 
Please click through the confirmation email.
Hit enter when done, or type 'resend': 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaraco/code/main/keyrings.firefox/keyrings/firefox.py", line 69, in login
    self._build_keys()
  File "/Users/jaraco/code/main/keyrings.firefox/keyrings/firefox.py", line 77, in _build_keys
    keys_bso = self.client.get_record("crypto", "keys")
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/syncclient/client.py", line 228, in get_record
    return self._request('get', '/storage/%s/%s' % (collection.lower(),
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/syncclient/client.py", line 116, in _request
    self.raw_resp = requests.request(method, url, auth=self.auth, **kwargs)
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests/models.py", line 372, in prepare
    self.prepare_auth(auth, url)
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests/models.py", line 603, in prepare_auth
    r = auth(self)
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/requests_hawk/__init__.py", line 81, in __call__
    sender = mohawk.Sender(
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/mohawk/sender.py", line 103, in __init__
    self.req_resource.gen_content_hash())
  File "/Users/jaraco/code/main/keyrings.firefox/.tox/python/lib/python3.10/site-packages/mohawk/base.py", line 284, in gen_content_hash
    raise MissingContent(
mohawk.exc.MissingContent: payload content and/or content_type cannot be empty when always_hash_content is True
```

**Comment by jaraco** [comment]
In IRC, Kane has suggested:

> I have done something in this regard with our fork of the old Python client (also includes the de-/encryption of BSOs apart from sync with OAuth) - was a nice experiment: https://github.com/eNote-GmbH/syncclient
>
> Please excuse the horrific code style. Stuff just added, never refactored/cleaned.
>
> ...more specifically, you just need the correct OAuth scope for the tokenserver to pass the auth checks and make sure to use an OAuth client-id that is allowed for that scope: https://github.com/eNote-GmbH/syncclient/blob/enote/syncclient/client.py#L374-L393

and 

> to "fake" a browser OAuth flow for FxA, the only thing that is needed is a real flow ID, which you can extract from almost any HTML: https://github.com/eNote-GmbH/syncclient/blob/enote/syncclient/client.py#L332-L360
>
> But this is only required for the actual login. Once you have a verified session, you can get OAuth tokens without any of these quirks.
